module.exports = [
    "Sword",
    "Bow",
    "Fire Staff",
    "Life Staff",
    "Hatchet",
    "Ice Gauntlet",
    "Musket",
    "Rapier",
    "Round Shield",
    "Great Axe",
    "Spear",
    "War Hammer",
    "Tower Shield",
    "Light HeadWear",
    "Medium HeadWear",
    "Heavy HeadWear",
    "Light Glove",
    "Medium Glove",
    "Heavy Glove",
    "Light ChestWear",
    "Medium ChestWear",
    "Heavy ChestWear",
]