module.exports = [
    "Abyssal",
    "Electrified",
    "Empowered",
    "Ignited",
    "Frozen",
    "Arboreal",
    "Brash",
    "Opportunist",
    "Retaliate",
    "Exhilarate",
    "Cruel",
    "Gambit",
    "Rally",
    "Abyssal Ward",
    "Fire Ward",
    "Lightning Ward",
    "Ice Ward",
    "Arcane Ward",
    "Nature Ward",
    "Slash Ward",
    "Strike Ward",
    "Thrust Ward",
    "Physical Ward",
    "Wilderness Ward",
    "Elemental Ward",
    "Spectral Ward",
    "Taunting",
    "Calming",
    "Lucky",
    "Fishing Colossus",
    "Lucky Waters",
    "Fishing Reach",
    "Lucky Day",
    "Lucky Night",
    "Sturdy",
    "Saltwaters Brawn",
    "Freshwaters Brawn",
    "Suns Reach",
    "Moons Reach",
    "Keen Berserk",
    "Refreshing Torrent",
    "Energizing Rending Throw",
    "Mending Infected Throw",
    "Daytime Colossus I",
    "Nightime Colossus I",
    "Saltwater Colossus I",
    "Freshwater Colossus",
    "Refreshing Mighty Gavel",
    "Penetrating Wrecking Ball",
    "Repulsing Clear Out",
    "Leeching Path Of Destiny",
    "Crippling Powder Burn",
    "Mending Sticky Bombs",
    "Sundering Javelin",
    "Bleeding Sweep",
    "Enfeebling Skewer",
    "Keen Vault Kick",
    "Enfeebling Poison Shot",
    "Energizing Evade Shot",
    "Fortifying Rain of Arrows",
    "Penetrating Rapid Shot",
    "Refreshing Penetrating Shot",
    "Keen Tondo",
    "Energizing Flourish",
    "Leeching Flurry",
    "Sundering Riposte",
    "Omnidirectional Evade",
    "Refreshing Divine Embrace",
    "Energizing Splash Of Light",
    "Mending Protection",
    "Accelerating Light's Embrace",
    "Efficient Burnout",
    "Empowering Fireball",
    "Accelerating Flamethrower",
    "Siphoning Incinerate",
    "Accelerated Defiant Stance",
    "Refeshing Charge",
    "Insatiable Gravity Well",
    "Mending Execute",
    "Fortifying Whirlwind",
    "Enfeebling Maelstrom",
    "Skinning Yield",
    "Contagious Reverse Stab",
    "Empowering Whirling Blade",
    "Empowering Leaping Strike",
    "Unbroken Winds",
    "Unending Thaw",
    "Refreshing",
    "Refreshing Ward",
    "Refreshing Evasion",
    "Durable",
    "Logging Luck",
    "Harvesting Luck",
    "Mining Luck",
    "Skinning Luck",
    "Logging Yield",
    "Harvesting Yield",
    "Mining Yield",
    "Ancient Ward",
    "Deadly Frost",
    "Healing Tomb",
    "Luck",
    "Horticulture Discipline",
    "Prospector's Discipline",
    "Gathering Alacrity",
    "Extra Pockets",
    "Gourmand's Burden",
    "Prospector's Burden",
    "Quarryman's Burden",
    "Weaver's Burden",
    "Tanner's Burden",
    "Mercenary's Burden",
    "Quartermaster's Burden",
    "Lumberjack's Burden",
    "Azoth Attuned",
    "Plentiful Arrows",
    "Plentiful Shells",
    "Loyalty",
    "Beast Ward",
    "Corrupted Ward",
    "Lost Ward",
    "Corruption Resistance",
    "Blight Resistance",
    "Resilient",
    "Reinforced",
    "Freedom",
    "Vigor",
    "Flame Protection",
    "Frozen Protection",
    "Nature Protection",
    "Void Protection",
    "Reinforced Harvesting Luck",
    "Reinforced Mining Luck",
    "Reinforced Skinning Luck",
    "Purify",
    "Lightning Protection",
    "Strike Protection",
    "Health",
    "Stamina Recovery",
    "Fortified Recovery",
    "Adored Logging Luck",
    "Adored Harvesting Luck",
    "Adored Mining Luck",
    "Adored Skinning Luck",
    "Empowered",
    "Alacrity",
    "Divine",
    "Siphoning",
    "Fire Damage",
    "Ice damage",
    "Nature damage",
    "Lightning Damage",
    "Void Damage",
    "Arcane Damage",
    "Thrust Damage",
    "Slash Damage",
    "Strike Damage",
    "Keen Awareness",
    "Poisoning",
    "Blood Letting",
    "Burning",
    "Crippling",
    "Hearty",
    "Brilliant",
    "Sacred",
    "Regenerating",
    "Focused",
    "Nimble",
    "Despised",
    "Beloved",
    "Mana Toast",
    "Purifying Toast",
    "Arcanist Mastery",
    "Refreshing Toast",
    "Evasive",
    "Armorer Mastery",
    "Cooking Mastery",
    "Engineer Mastery",
    "Kind",
    "Vicious",
    "Enchanted",
    "Rogue",
    "Ruinous",
    "Blessed",
    "Refreshing Move",
    "Lifestealing",
    "Jewelcrafter Mastery",
    "Weaponsmith Mastery",
    "Keenly Jagged",
    "Keenly Empowered",
    "Keen Speed",
    "Mortal Fortification",
    "Mortal Energy",
    "Keen",
    "Ancient Bane",
    "Angry Earth Bane",
    "Beast Bane",
    "Chain Lightning",
    "Chain Fire",
    "Chain Void",
    "Chain Ice",
    "Chain Nature",
    "Mortal Power",
    "Mortal Refreshment",
    "Lost Bane",
    "Accuracy",
    "Vorpal",
    "Sure Footing",
    "Flame Shield Ward",
    "Frozen Shield Ward",
    "Nature Shield Ward",
    "Void Shield Ward",
    "Thrust Shield Ward",
    "Slash Shield Ward",
    "Arcane Shield Ward",
    "Lightning Shield Ward",
    "Strike Shield Ward",
    "Arcanist Expertise",
    "Armorer Expertise",
    "Cooking Expertise",
    "Engineer Expertise",
    "Jewelcrafter Expertise",
    "Leeching Cyclone",
    "Fortifying Perforate",
    "Refreshing Fleche",
    "Fortifying Sacred Ground",
    "Repulsing Shield Bash",
    "Fortifying Shield Rush",
    "Weaponsmith Expertise",
    "Stonecutting Accumulation",
    "Leatherworking Accumulation",
    "Smelting Accumulation",
    "Weaving Accumulation",
    "Woodworking Accumulation",
    "Lumberjack's Discipline",
    "Angry Earth Ward",
    "Thrust Protection",
    "Fortified",
    "Infected",
    "Healthy Toast",
    "Hated",
    "Mortal Lifesteal",
    "Corrupted Bane",
    "Energizing Feral Rush",
    "Vorpal Distancing Throw",
    "Empowering Armor Breaker",
    "Sundering Shockwave",
    "Empowering Shooter's Stance",
    "Energizing Stopping Power",
    "Accelerating Traps",
    "Empowering Splinter Shot",
    "Revitializing Beacon",
    "Refreshing Pillar of Fire",
    "Empowering Meteor Shower",
    "Crippling Reap",
    "Iced Refresh",
    "Pylon Burst",
    "Azoth Extraction",
    "Tanner's Discipline",
    "Alchemist's Burden",
    "Reinforced Logging Luck",
    "Invigorated",
    "Slash Protection",
    "Arcane Protection",
    "Mana Recovery",
    "Leeching",
    "Enfeebling",
    "Duplicating Toast",
    "Keenly Fortified",
    "Siphoning Blow",
    "Chain Arcane",
    "Mortal Siphoning",
    "Sturdy"
]